# Generated by Django 2.0.3 on 2019-06-11 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='salida',
            field=models.CharField(default=datetime.datetime(2019, 6, 11, 10, 6, 38, 92206), max_length=150),
        ),
    ]
