# Generated by Django 2.0.3 on 2019-06-02 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_categoria_material_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='salida',
            field=models.CharField(default=datetime.datetime(2019, 6, 2, 15, 50, 0, 212662), max_length=150),
        ),
    ]
