# Generated by Django 2.2.1 on 2019-05-30 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('rol', models.CharField(choices=[('MA', 'Maestro'), ('AL', 'Alumno')], default='AL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
                ('hora_salida', models.TimeField(default=datetime.time)),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.User')),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('apartado', models.BooleanField(default=False)),
                ('img', models.CharField(default='img.png', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Categoria')),
            ],
        ),
    ]
