# Generated by Django 2.2.1 on 2019-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
