# Generated by Django 2.2.1 on 2019-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20190528_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='img',
            field=models.CharField(default='img.png', max_length=50),
        ),
    ]
